import { createSlice } from "@reduxjs/toolkit";
import timetable from "../assets/icons/timetable.svg";
import roomOrdering from "../assets/icons/roomOrdering.svg";
import houseRenting from "../assets/icons/houseRenting.svg";
import vacancy from "../assets/icons/vacancy.svg";
import canteen from "../assets/icons/canteen.svg";
import freeCourse from "../assets/icons/freeCourse.svg";
import library from "../assets/icons/library.svg";
import aboutInstitute from "../assets/icons/aboutInstitute.svg";
import student from "../assets/icons/student.svg";
import cover1 from "../assets/books/cover1.svg";
import cover2 from "../assets/books/cover2.svg";
import cover3 from "../assets/books/cover3.svg";
import cover4 from "../assets/books/cover4.svg";
import cover5 from "../assets/books/cover5.svg";
import cover6 from "../assets/books/cover6.svg";
import cover7 from "../assets/books/cover7.svg";
import flat1 from "../assets/flats/flat1.svg";
import flat2 from "../assets/flats/flat2.svg";
import flat3 from "../assets/flats/flat3.svg";
import flat4 from "../assets/flats/flat4.svg";
import news1 from "../assets/news/news1.svg";
import news2 from "../assets/news/news2.svg";
import news3 from "../assets/news/news3.svg";
import cafe1 from "../assets/canteen/cafe1.png";
import vacancy1 from "../assets/vacancy/vacancy1.png";
import timetableImg from "../assets/timetable/timetable.svg";
import math from "../assets/courses/math.jpg";
import engineering from "../assets/courses/engineering.jpeg";
import physics from "../assets/courses/physics.png";
import programming from "../assets/courses/programming.jpg";
import agro from "../assets/courses/agro.jpg";

const initialState = {
  departments: [
    {
      id: 1,
      title: "Dars jadvali",
      body: "Joriy yildagi barcha kurslar uchun darslar jadvali",
      link: "/timetable",
      img: timetable,
    },
    {
      id: 2,
      title: "Xonalar joylashuvi",
      body: "O’quv bo’limlari va ma’muriy bo’lim xodimlarining xonalari joylashuvi",
      link: "/room_ordering",
      img: roomOrdering,
    },
    {
      id: 3,
      title: "Ijaraga uylar",
      body: "Ijara uchun yaqn atrofdagi yoki arzon narxdagi uylar ro’yxati",
      link: "/house_renting",
      img: houseRenting,
    },
    {
      id: 4,
      title: "Bo’sh ish o’rinlari",
      body: "Institutdagi va hamkor tashkilotlardagi maavjud ish vakansiyalari",
      link: "/vacancies",
      img: vacancy,
    },
    {
      id: 5,
      title: "Oshxona va kafelar",
      body: "Atrofdagi arzon oshxona va kafelarning joylashuvi va narxlari",
      link: "/canteens_and_cafes",
      img: canteen,
    },
    {
      id: 6,
      title: "To’garaklar ro’yxati",
      body: "Institutdagi bepul va pullik to’garaklarning ro’yxati",
      link: "/free_courses",
      img: freeCourse,
    },
    {
      id: 7,
      title: "Kutubxona",
      body: "O’quv qollanmalari, darsliklar va badiiy adibiyotlar jamlanmasi",
      link: "/library",
      img: library,
    },
    {
      id: 8,
      title: "Institut haqida",
      body: "Institut tarixi, web sahifalari, va ma’muriy xodimlari haqida ma’lumot",
      link: "/about_institute",
      img: aboutInstitute,
    },
    {
      id: 9,
      title: "Iqtidorli talabalar",
      body: "Institutdagi faol, iqtidorli va bilimdon talabalarni sarab bo’limi",
      link: "/",
      img: student,
    },
  ],
  most_read_books: [
    {
      id: 1,
      cover: cover1,
      info: "first book",
    },
    {
      id: 2,
      cover: cover2,
      info: "second book",
    },
    {
      id: 3,
      cover: cover3,
      info: "third book",
    },
    {
      id: 4,
      cover: cover4,
      info: "fourth book",
    },
    {
      id: 5,
      cover: cover5,
      info: "fifth book",
    },
    {
      id: 6,
      cover: cover6,
      info: "sixth book",
    },
    {
      id: 7,
      cover: cover7,
      info: "seventh book",
    },
    {
      id: 8,
      cover: cover1,
      info: "eighth book",
    },
  ],
  flats: [
    {
      id: 1,
      img: flat1,
      title: "Hovli",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "200 000 so‘m",
    },
    {
      id: 2,
      img: flat2,
      title: "Ko’p qavatli uy",
      location: "Andijon shahar, Teshavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 343 45 56",
      requirement: "Ijaraga faqat student qizlar qo’yiladi",
      condition: "Gaz, dars xonasi, oshxona, yuvinish xonasi, internet ",
      owner: "Yuldoshev Aslbek",
      cost: "250 000 so‘m",
    },
    {
      id: 3,
      img: flat3,
      title: "Dacha",
      location: "Toshtemir ko’chasi, kafe ro’parasi",
      call_number: "+998 90 123 45 67",
      requirement: "Ijaraga student qizlar ham bolalar ham qo'yiladi",
      condition: "Yotoqxona, hammom, wifi , muzlatkich, dam olish maskani",
      owner: "Sodiqov Otabek",
      cost: "400 000 so‘m",
    },
    {
      id: 4,
      img: flat4,
      title: "Ko'p Qavatli Uy",
      location: "Andijon shahar, Asaka zavodi ro'parasida",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi , gaz , duxovka",
      owner: "Yunusov Elshod",
      cost: "220 000 so‘m",
    },
    {
      id: 5,
      img: flat1,
      title: "Hovli",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "200 000 so‘m",
    },
    {
      id: 6,
      img: flat2,
      title: "Hovli",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "200 000 so‘m",
    },
    {
      id: 7,
      img: flat3,
      title: "Hovli",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "200 000 so‘m",
    },
    {
      id: 8,
      img: flat4,
      title: "Hovli",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "200 000 so‘m",
    },
    {
      id: 9,
      img: flat2,
      title: "Ko'p qavatli uy",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "300 000 so‘m",
    },
    {
      id: 10,
      img: flat1,
      title: "Hovli",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "200 000 so‘m",
    },
    {
      id: 11,
      img: flat1,
      title: "Hovli",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "200 000 so‘m",
    },
    {
      id: 12,
      img: flat3,
      title: "Hovli",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi",
      call_number: "+998 99 123 45 67",
      requirement: "Ijaraga faqat student yigitlar qo’yiladi",
      condition: "Yotoqxona, hammom, wifi",
      owner: "Teshaboyev Boltavoy ",
      cost: "200 000 so‘m",
    },
  ],
  news: [
    {
      id: 1,
      title: "Texnologiya",
      body: "Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi? Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi?",
      img: news1,
    },
    {
      id: 2,
      title: "Mukofotlar",
      body: "Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi? Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi?",
      cover: news3,
    },
    {
      id: 3,
      title: "Mukofotlar",
      body: "Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi? Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi?",
      cover: news3,
    },
    {
      id: 4,
      title: "Texnologiya",
      body: "Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi? Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi?",
      img: news2,
    },
    {
      id: 5,
      title: "Texnologiya",
      body: "Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi? Mening navbatim keldimi? Ovozli yordamchiga qachon gapirishni o'rgatish Hali mening navbatimmi?",
      img: news1,
    },
  ],
  books: [
    {
      id: 1,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover1,
      category: "darsliklar",
    },
    {
      id: 2,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover1,
      category: "darsliklar",
    },
    {
      id: 3,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover1,
      category: "darsliklar",
    },
    {
      id: 4,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover1,
      category: "darsliklar",
    },
    {
      id: 5,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover1,
      category: "darsliklar",
    },
    {
      id: 6,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover1,
      category: "darsliklar",
    },
    {
      id: 7,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover1,
      category: "darsliklar",
    },
    {
      id: 8,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover2,
      category: "badiy kitoblar",
    },
    {
      id: 9,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover2,
      category: "badiy kitoblar",
    },
    {
      id: 10,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover2,
      category: "badiy kitoblar",
    },
    {
      id: 11,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover2,
      category: "badiy kitoblar",
    },
    {
      id: 12,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover2,
      category: "badiy kitoblar",
    },
    {
      id: 13,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover2,
      category: "badiy kitoblar",
    },
    {
      id: 14,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover2,
      category: "badiy kitoblar",
    },
    {
      id: 15,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover2,
      category: "badiy kitoblar",
    },
    {
      id: 16,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
    {
      id: 17,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
    {
      id: 18,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
    {
      id: 19,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
    {
      id: 20,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
    {
      id: 21,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
    {
      id: 22,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
    {
      id: 23,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
    {
      id: 24,
      name: "Свободу мозгу",
      author: "Идрис Аверкин",
      cover: cover3,
      category: "oquv qollanmalari",
    },
  ],
  canteens: [
    {
      id: 1,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 2,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 3,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 4,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 5,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 6,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 7,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 8,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 9,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 10,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 11,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 12,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 12,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 14,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 15,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 16,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 17,
      name: "osh markazi",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "08:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
    {
      id: 18,
      name: "Kamolon",
      location: "Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      work_time: "10:00 - 18:00",
      menu: "Dolma, Shorva, Osh, Lagmo’n, Shashli, Somsa, Chuchvara",
      img: cafe1,
    },
  ],
  vacancies: [
    {
      id: 1,
      office: "Sanis",
      work: "Tikuvchilik",
      free_space: "2",
      work_time: "Dushanba - Juma,  08:00 - 18:00 ",
      opportunity: "1 Mahal ovqat, Yol harajati",
      location: "Manzil: Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      cost: "1 000 000 so‘m",
      number: "+998 90 255 55 55 ",
      img: vacancy1,
    },
    {
      id: 2,
      office: "Sanis",
      work: "Tikuvchilik",
      free_space: "2",
      work_time: "Dushanba - Juma,  08:00 - 18:00 ",
      opportunity: "1 Mahal ovqat, Yol harajati",
      location: "Manzil: Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      cost: "1 000 000 so‘m",
      number: "+998 90 255 55 55 ",
      img: vacancy1,
    },
    {
      id: 3,
      office: "Sanis",
      work: "Tikuvchilik",
      free_space: "2",
      work_time: "Dushanba - Juma,  08:00 - 18:00 ",
      opportunity: "1 Mahal ovqat, Yol harajati",
      location: "Manzil: Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      cost: "1 000 000 so‘m",
      number: "+998 90 255 55 55 ",
      img: vacancy1,
    },
    {
      id: 4,
      office: "Sanis",
      work: "Tikuvchilik",
      free_space: "2",
      work_time: "Dushanba - Juma,  08:00 - 18:00 ",
      opportunity: "1 Mahal ovqat, Yol harajati",
      location: "Manzil: Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      cost: "1 000 000 so‘m",
      number: "+998 90 255 55 55 ",
      img: vacancy1,
    },
    {
      id: 5,
      office: "Sanis",
      work: "Tikuvchilik",
      free_space: "2",
      work_time: "Dushanba - Juma,  08:00 - 18:00 ",
      opportunity: "1 Mahal ovqat, Yol harajati",
      location: "Manzil: Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      cost: "1 000 000 so‘m",
      number: "+998 90 255 55 55 ",
      img: vacancy1,
    },
    {
      id: 6,
      office: "Sanis",
      work: "Tikuvchilik",
      free_space: "2",
      work_time: "Dushanba - Juma,  08:00 - 18:00 ",
      opportunity: "1 Mahal ovqat, Yol harajati",
      location: "Manzil: Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      cost: "1 000 000 so‘m",
      number: "+998 90 255 55 55 ",
      img: vacancy1,
    },
    {
      id: 7,
      office: "Sanis",
      work: "Tikuvchilik",
      free_space: "2",
      work_time: "Dushanba - Juma,  08:00 - 18:00 ",
      opportunity: "1 Mahal ovqat, Yol harajati",
      location: "Manzil: Andijon shahar, Boltavoy ko’chasi, kafe ro’parasi ",
      cost: "1 000 000 so‘m",
      number: "+998 90 255 55 55 ",
      img: vacancy1,
    },
  ],
  courses: [
    {
      id: 1,
      course: "1-kurs",
    },
    {
      id: 2,
      course: "2-kurs",
    },
    {
      id: 3,
      course: "3-kurs",
    },
    {
      id: 4,
      course: "4-kurs",
    },
  ],
  faculties: [
    {
      id: 1,
      faculty: "Agrotexnologiyalar",
    },
    {
      id: 2,
      faculty: "Qishloq Xo'jaligi",
    },
    {
      id: 3,
      faculty: "Muhandislik",
    },
  ],
  fields: [
    {
      id: 1,
      faculty: "Something",
    },
    {
      id: 2,
      faculty: "Another thing",
    },
    {
      id: 3,
      faculty: "Third thing",
    },
  ],
  timetables: [
    {
      id: 1,
      title: "2-8 Sentyabr 2022",
      content: timetableImg,
    },
    {
      id: 2,
      title: "2-8 Sentyabr 2023",
      content: timetableImg,
    },
  ],
  free_courses: [
    {
      id: 1,
      science: "Matematika",
      prof: "Otabek Sodiqov",
      capacity: "25 kishi",
      number: "+998 93 684 37 57",
      time: "16:00 - 18:00",
      img: math,
      full_info:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Commodi eum quasi inventore?",
    },
    {
      id: 2,
      science: "Injineriya",
      prof: "Mirshod Murodov",
      capacity: "15 kishi",
      number: "+998 94 683 12 32",
      time: "12:00 - 13:00",
      img: engineering,
      full_info:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia ratione in ipsa iste veniam saepe nihil itaque recusandae nemo harum!",
    },
    {
      id: 3,
      science: "Fizika",
      prof: "Dilshod Murodov",
      capacity: "12 kishi",
      number: "+998 94 683 18 32",
      time: "13:00 - 15:00",
      img: physics,
      full_info:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati, repellendus! Quae qui enim cupiditate et sit esse laborum quo, totam expedita, consequatur autem a quaerat.",
    },
    {
      id: 4,
      science: "Dasturlash",
      prof: "Ulug'bek Temirov",
      capacity: "18 kishi",
      number: "+998 97 123 87 43",
      time: "17:00 - 19:00",
      img: programming,
      full_info:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum nostrum nam suscipit deserunt! Magni modi corporis mollitia ab nulla doloremque quod illo tempora iure recusandae? Excepturi ad dolore voluptatem beatae sit quia.",
    },
    {
      id: 5,
      science: "Agrotexnologiya",
      prof: "Jamshid Toshov",
      capacity: "100 kishi",
      number: "+998 99 876 10 20",
      time: "15:00 - 18:00",
      img: agro,
      full_info:
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magni nobis quidem explicabo aperiam ipsa, quaerat, a impedit eos et officia quas saepe totam aut! Nobis fuga earum architecto eveniet vel voluptate quibusdam, magni possimus quaerat quia autem. Recusandae asperiores dolorum nisi saepe vel voluptates vitae.",
    },
  ],
};

export const dataSlice = createSlice({
  name: "dataSlice",
  initialState,
  reducers: {},
});

export const {} = dataSlice.actions;
export default dataSlice.reducer;
